# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)

mod_id=createredstonelinkgui
mod_name=Create: Redstone Link GUI
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.20.1-1.6.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.ggrgg.createredstonelinkgui

create_version=6.0.8-291
create_version_range=[6.0.8,6.1)
ponder_version=1.0.92
flywheel_version=1.0.6-278
registrate_version=MC1.20-1.3.11

jei_version=15.20.0.106
jei_version_range=[15,)

emi_version=1.1.22+1.20.1
emi_version_range=[1.1.22,)
